apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args:
            - "--save"
            - ""
            - "--appendonly"
            - "no"
            - "--maxmemory"
            - "100mb"
            - "--maxmemory-policy"
            - "allkeys-lru"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secret
                  key: redis-password
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: url-shortener
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
